name: Aylık Vakit Güncelleyici
on:
  schedule:
    - cron: '0 0 25 * *' # Her ayın 25'inde gece uyanır
  workflow_dispatch: # Manuel çalıştırman için buton açar

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: Python Hazırla
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Gerekli Kütüphaneleri Yukle
        run: |
          pip install requests requests-cache beautifulsoup4

      - name: Dunya Vakitlerini Topla
        run: |
          # Verilerin kaydedileceği klasörü zorla oluşturuyoruz
          mkdir -p static
          
          # Dosyayı bul ve çalıştır
          MAIN_FILE=$(find . -name "main.py" | grep "ezanvakti_api" | head -n 1)
          export PYTHONPATH=$PYTHONPATH:$(dirname $(dirname $MAIN_FILE))
          
          # Çıktı klasörünü açıkça belirtiyoruz
          python3 $MAIN_FILE
        env:
          OUTPUT_DIR: 'static'

      - name: R2 Deposuna Yukle
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.R2_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          AWS_ENDPOINT: https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
          SOURCE_DIR: 'static'
